### ISSUE TITLE
Can't select downloads folder

### ISSUE THREAD

**Issue by watashibeme** [avluis/Hentoid#1006]
Selecting downloads folder from welcome screen, leads to app not responding and having to force close

Skipping and later selecting download folder from settings--storage, leads to same result

This log only contains one of the above methods, since startup screen and settings act similarly

Pastebin of same log:
`https://pastebin.com/ttnCAhMB`

```
<<< log_count = 52 >>>
[08-18 02:07:54.476 2577:13532 I/ActivityTaskManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=me.devsaki.hentoid/.activities.SplashActivity bnds=[843,1252][1045,1579]} from uid 10212

[08-18 02:07:54.502 2577:2670 I/ActivityManager]
Start proc 15566:me.devsaki.hentoid/u0a153 for pre-top-activity {me.devsaki.hentoid/me.devsaki.hentoid.activities.SplashActivity}

[08-18 02:07:54.532 15566:15566 V/GraphicsEnvironment]
ANGLE Developer option for 'me.devsaki.hentoid' set to: 'default'

[08-18 02:07:54.533 15566:15566 V/GraphicsEnvironment]
ANGLE GameManagerService for me.devsaki.hentoid: false

[08-18 02:07:54.610 15566:22384 I/cr_VariationsUtils]
Failed reading seed file "/data/user/0/me.devsaki.hentoid/app_webview/variations_seed_new"

[08-18 02:07:54.610 15566:22377 I/FA]
To enable faster debug mode event logging run:
  adb shell setprop debug.firebase.analytics.app me.devsaki.hentoid

[08-18 02:07:54.681 2577:2670 I/ActivityManager]
Start proc 22392:com.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0i34 for  {me.devsaki.hentoid/org.chromium.content.app.SandboxedProcessService0:0}

[08-18 02:07:54.836 2577:2655 I/ActivityTaskManager]
Displayed me.devsaki.hentoid/.activities.SplashActivity: +355ms

[08-18 02:07:54.986 2577:13532 I/ActivityTaskManager]
START u0 {cmp=me.devsaki.hentoid/.activities.IntroActivity} from uid 10153

[08-18 02:07:55.094 2577:2655 I/ActivityTaskManager]
Displayed me.devsaki.hentoid/.activities.IntroActivity: +105ms

[08-18 02:07:55.098 15566:15566 I/WM-SystemFgDispatcher]
Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=me.devsaki.hentoid/androidx.work.impl.foreground.SystemForegroundService (has extras) }

[08-18 02:07:55.127 15566:22440 D/EventBus]
No subscribers registered for event class me.devsaki.hentoid.events.ServiceDestroyedEvent

[08-18 02:07:55.129 15566:22376 I/WM-WorkerWrapper]
Worker result SUCCESS for Work [ id=dc6225ce-d244-45b1-a412-b5559fc06116, tags={ me.devsaki.hentoid.workers.StartupWorker } ]

[08-18 02:07:55.201 2577:13359 W/InputManager-JNI]
Input channel object '2e6cacc Splash Screen me.devsaki.hentoid (client)' was disposed without first being removed with the input manager!

[08-18 02:07:55.301 2577:2577 I/NotificationService]
Cannot find enqueued record for key: 0|me.devsaki.hentoid|2131297181|null|10153

[08-18 02:07:55.304 2577:2577 I/NotificationService]
Cannot find enqueued record for key: 0|me.devsaki.hentoid|2131297181|null|10153

[08-18 02:07:55.306 2577:2577 I/NotificationService]
Cannot find enqueued record for key: 0|me.devsaki.hentoid|2131297181|null|10153

[08-18 02:07:55.312 2577:13561 W/InputManager-JNI]
Input channel object 'cf495fd me.devsaki.hentoid/me.devsaki.hentoid.activities.SplashActivity (client)' was disposed without first being removed with the input manager!

[08-18 02:07:55.314 2577:2577 I/NotificationService]
Cannot find enqueued record for key: 0|me.devsaki.hentoid|2131297181|null|10153

[08-18 02:07:55.318 3456:3502 D/PeopleSpaceWidgetMgr]
Sbn doesn't contain valid PeopleTileKey: null/0/me.devsaki.hentoid

[08-18 02:07:55.319 2577:2577 I/NotificationService]
Cannot find enqueued record for key: 0|me.devsaki.hentoid|2131297181|null|10153

[08-18 02:07:55.319 2577:2577 I/NotificationService]
Cannot find enqueued record for key: 0|me.devsaki.hentoid|2131297181|null|10153

[08-18 02:07:55.319 2577:2577 I/NotificationService]
Cannot find enqueued record for key: 0|me.devsaki.hentoid|2131297181|null|10153

[08-18 02:07:55.320 2577:2577 I/NotificationService]
Cannot find enqueued record for key: 0|me.devsaki.hentoid|2131297181|null|10153

[08-18 02:07:55.325 2577:2577 I/NotificationService]
Cannot find enqueued record for key: 0|me.devsaki.hentoid|2131297181|null|10153

[08-18 02:07:55.329 2577:2577 I/NotificationService]
Cannot find enqueued record for key: 0|me.devsaki.hentoid|2131297181|null|10153

[08-18 02:07:55.330 2577:2577 I/NotificationService]
Cannot find enqueued record for key: 0|me.devsaki.hentoid|2131297181|null|10153

[08-18 02:07:56.010 2577:2655 D/CompanionDeviceManagerService]
onPackageModified(packageName = me.devsaki.hentoid)

[08-18 02:07:56.016 31539:31539 D/BR_REC]
Received: Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:me.devsaki.hentoid flg=0x45000010 (has extras) } with action 'android.intent.action.PACKAGE_CHANGED'

[08-18 02:07:56.037 3752:3752 D/ImsResolver]
maybeAddedImsService, packageName: me.devsaki.hentoid

[08-18 02:07:56.049 19327:22456 I/Fitness]
OnPackageChangedOperation got intent: Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:me.devsaki.hentoid flg=0x45000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) } [CONTEXT service_id=17 ]

[08-18 02:07:56.118 15566:15566 D/EventBus]
No subscribers registered for event class me.devsaki.hentoid.events.UpdateEvent

[08-18 02:07:56.128 3456:3502 D/PeopleSpaceWidgetMgr]
Sbn doesn't contain valid PeopleTileKey: null/0/me.devsaki.hentoid

[08-18 02:07:56.536 15566:15566 W/FinalizerDaemon]
type=1400 audit(0.0:4592): avc: denied { getopt } for path="/dev/socket/usap_pool_primary" scontext=u:r:untrusted_app:s0:c153,c256,c512,c768 tcontext=u:r:zygote:s0 tclass=unix_stream_socket permissive=0 app=me.devsaki.hentoid

[08-18 02:07:59.168 15566:15566 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: me.devsaki.hentoid, PID: 15566
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2117)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1762)
	at android.app.Activity.startActivityForResult(Activity.java:5410)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:239)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
	at androidx.fragment.app.Fragment$9.launch(Fragment.java:3507)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at me.devsaki.hentoid.fragments.intro.ImportIntroFragment.onViewCreated$lambda-1(ImportIntroFragment.kt:96)
	at me.devsaki.hentoid.fragments.intro.ImportIntroFragment.$r8$lambda$h8TNM-Ux7p-U0Z4lGqwbhrt-gCY(Unknown Source:0)
	at me.devsaki.hentoid.fragments.intro.ImportIntroFragment$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

[08-18 02:08:43.462 2577:3323 W/InputDispatcher]
Window 122314d me.devsaki.hentoid/me.devsaki.hentoid.activities.IntroActivity (server) is unresponsive: 122314d me.devsaki.hentoid/me.devsaki.hentoid.activities.IntroActivity (server) is not responding. Waited 5004ms for MotionEvent(deviceId=2, eventTime=37905182931000, source=0x00001002, displayId=0, action=DOWN, actionButton=0x00000000, flags=0x00000800, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=8.0, yPrecision=8.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (364.9, 1217.1)]), policyFlags=0x67020000

[08-18 02:08:43.462 2577:3323 W/InputDispatcher]
Canceling events for 122314d me.devsaki.hentoid/me.devsaki.hentoid.activities.IntroActivity (server) because it is unresponsive

[08-18 02:08:43.467 2577:3323 I/WindowManager]
ANR in Window{122314d u0 me.devsaki.hentoid/me.devsaki.hentoid.activities.IntroActivity}. Reason:122314d me.devsaki.hentoid/me.devsaki.hentoid.activities.IntroActivity (server) is not responding. Waited 5004ms for MotionEvent(deviceId=2, eventTime=37905182931000, source=0x00001002, displayId=0, action=DOWN, actionButton=0x00000000, flags=0x00000800, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=8.0, yPrecision=8.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (364.9, 1217.1)]), policyFlags=0x67020000

[08-18 02:08:46.933 2577:22672 E/ActivityManager]
ANR in me.devsaki.hentoid (me.devsaki.hentoid/.activities.IntroActivity)
PID: 15566
Reason: Input dispatching timed out (122314d me.devsaki.hentoid/me.devsaki.hentoid.activities.IntroActivity (server) is not responding. Waited 5004ms for MotionEvent(deviceId=2, eventTime=37905182931000, source=0x00001002, displayId=0, action=DOWN, actionButton=0x00000000, flags=0x00000800, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=8.0, yPrecision=8.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (364.9, 1217.1)]), policyFlags=0x67020000)
Parent: me.devsaki.hentoid/.activities.IntroActivity
ErrorId: b4425682-384b-4240-b6d4-c1b6d8cfe36c
Frozen: false
Load: 0.0 / 0.07 / 0.11
----- Output from /proc/pressure/memory -----
some avg10=0.00 avg60=0.00 avg300=0.03 total=33521105
full avg10=0.00 avg60=0.00 avg300=0.00 total=15479806
----- End output from /proc/pressure/memory -----

[08-18 02:08:46.936 2577:22672 D/ActivityManager]
Completed ANR of me.devsaki.hentoid in 3397ms, latency 1ms

[08-18 02:08:49.590 2577:2656 W/ActivityTaskManager]
  Force finishing activity me.devsaki.hentoid/.activities.IntroActivity

[08-18 02:08:49.601 2577:2656 I/ActivityManager]
Killing 15566:me.devsaki.hentoid/u0a153 (adj 0): user request after error

[08-18 02:08:49.620 2577:2656 W/InputManager-JNI]
Input channel object '1397ee1 Application Not Responding: me.devsaki.hentoid (client)' was disposed without first being removed with the input manager!

[08-18 02:08:49.671 2577:2614 I/WindowManager]
WIN DEATH: Window{122314d u0 me.devsaki.hentoid/me.devsaki.hentoid.activities.IntroActivity}

[08-18 02:08:49.671 2577:2614 W/InputManager-JNI]
Input channel object '122314d me.devsaki.hentoid/me.devsaki.hentoid.activities.IntroActivity (client)' was disposed without first being removed with the input manager!

[08-18 02:08:49.677 2577:15467 W/InputManager-JNI]
Input channel object 'Letterbox_left_ActivityRecord{380f19e u0 me.devsaki.hentoid/.activities.IntroActivity t491} (client)' was disposed without first being removed with the input manager!

[08-18 02:08:49.678 2577:15467 W/InputManager-JNI]
Input channel object 'Letterbox_top_ActivityRecord{380f19e u0 me.devsaki.hentoid/.activities.IntroActivity t491} (client)' was disposed without first being removed with the input manager!

[08-18 02:08:49.678 2577:15467 W/InputManager-JNI]
Input channel object 'Letterbox_right_ActivityRecord{380f19e u0 me.devsaki.hentoid/.activities.IntroActivity t491} (client)' was disposed without first being removed with the input manager!

[08-18 02:08:49.678 2577:15467 W/InputManager-JNI]
Input channel object 'Letterbox_bottom_ActivityRecord{380f19e u0 me.devsaki.hentoid/.activities.IntroActivity t491} (client)' was disposed without first being removed with the input manager!

[08-18 02:08:49.681 2577:13532 W/InputDispatcher]
Letterbox_top_ActivityRecord{380f19e u0 me.devsaki.hentoid/.activities.IntroActivity t491} has FLAG_SLIPPERY. Please report this in b/157929241

[08-18 02:08:49.703 2577:2659 W/WindowManager]
Failed to deliver inset state change to w=Window{122314d u0 me.devsaki.hentoid/me.devsaki.hentoid.activities.IntroActivity EXITING}
android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:571)
	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:687)
	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:4037)
	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$6$InsetsStateController(InsetsStateController.java:552)
	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:226)
	at com.android.server.wm.WindowAnimator.lambda$new$1$WindowAnimator(WindowAnimator.java:106)
	at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda0.doFrame(Unknown Source:2)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:775)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:44)

[08-18 02:08:50.091 2577:2658 W/ActivityTaskManager]
Activity top resumed state loss timeout for ActivityRecord{380f19e u0 me.devsaki.hentoid/.activities.IntroActivity t-1 f}}


```

Info:
App version:latest github release
Device:Poco F3,Android 12, LineageOS

**Comment by RobbWatershed** [comment]
Thanks a lot for the detailed log.

Looks like you're in that category: https://github.com/avluis/Hentoid/wiki/FAQ#Misc-9

**Comment by watashibeme** [comment]
> Thanks a lot for the detailed log.
> 
> Looks like you're in that category: https://github.com/avluis/Hentoid/wiki/FAQ#q--the-app-force-closes-when-choosing-the-hentoid-folder-how-to-solve-it-

Haven't seen this.. I'll be trying that guide. Upin successful resolve of problem, will close this issue.. Thanks :)

**Comment by watashibeme** [comment]
Damn.. I know the problem was from documentsUI(Files), because I have installed a systemizer for mixplorer(which deletes DocumentsUI in return)

**Comment by watashibeme** [comment]
@RobbWatershed isn't it possible to ask the system, instead of opening documentsUI?

**Comment by RobbWatershed** [comment]
I don't ask for DocumentsUI. I'm actually asking the system, which relies on DocumentsUI as it is bundled with vanilla Android.

Could you point to an open-source app that lets you pick a _folder_ with a 3rd party file explorer ?

**Comment by watashibeme** [comment]
Hmmm..

It seems that there isn't any...that I know of

I don't have Android programming experience, just throwing ideas around, and thought apps like hentoid are defaulting to DocumentsU, Im not sure, but when I had removed the documentsUI, some apps were asking me for which app to use(possibly because they didn't find the DocumentsUI?)
Since I have already selected the downloads location, I would delete DocumentsUI again to see if there is foss app that would ask

**Comment by watashibeme** [comment]
DocumentsUI is required - Android API 30+ uses Storage Access Framework (SAF), which requires DocumentsUI to grant access to the device storage.

Hmmm... So it's not really possible, is it?

My bad :)

**Comment by RobbWatershed** [comment]
That's about it. And don't mistake file pickers for folder pickers. Here we do need a _folder_ picker to grant access to the storage.

**Comment by watashibeme** [comment]
I see
