### ISSUE TITLE
`External library > Change location...` makes the app restart on Android 13

### ISSUE THREAD

**Issue by Retia-Adolf** [avluis/Hentoid#1086]
**Hentoid Version**: 1.18.1

**Device/Android Version**: Android 13

**Issue details / Repro steps**:
`Settings > Storage > Storage management > External library > Change location...` immediately restarts app after tapping.

Path has been set at `/storage/emulated/0/.Hentoid-Old`.

Refresh location works fine though.

No any permission denied in app info page, but Hentoid doesn't seem to require any permission related to storage either.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for your feeedback

**Comment by RobbWatershed** [comment]
Could you share `Tool > App logs > latest_crash` to get the stacktrace of what happens ?

**Comment by Retia-Adolf** [comment]
```
latest-crash log : begin
Hentoid ver: 1.18.1 (665)
API: 33
Device: Phone 2
Start : 2023-08-08T08:42:39.002Z
End : 2023-08-08T08:42:39.003Z (00:00)
-----
No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE (has extras) }
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2206)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1845)
	at android.app.Activity.startActivityForResult(Activity.java:5507)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:860)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:249)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:243)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:175)
	at androidx.fragment.app.Fragment$10.launch(Fragment.java:3612)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at me.devsaki.hentoid.fragments.preferences.LibRefreshDialogFragment.pickFolder(LibRefreshDialogFragment.kt:283)
	at me.devsaki.hentoid.fragments.preferences.LibRefreshDialogFragment.showImportProgressLayout(LibRefreshDialogFragment.kt:264)
	at me.devsaki.hentoid.fragments.preferences.LibRefreshDialogFragment.onViewCreated(LibRefreshDialogFragment.kt:140)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

latest-crash log : end
```

**Comment by RobbWatershed** [comment]
Aha... that one might be because you fiddled with your default file explorer.

You may find a solution in the dedicated FAQ : https://github.com/avluis/Hentoid/wiki/FAQ#q--the-app-force-closes-when-choosing-the-hentoid-folder-how-to-solve-it
