### ISSUE TITLE
Queueing, downloading and deleting not working/crashing the app

### ISSUE THREAD

**Issue by ImAWerewolfDuck** [avluis/Hentoid#1096]
**Hentoid Version**:
1.18.3

**Device/Android Version**:
Oneplus 7 Pro, Android 12

**Issue details / Repro steps**:
Suddenly had this problems, updating the app also did not work:
When viewing a manga, the "add to queue" button does not appear after viewing a manga (long press queueing does also not work). Turning the augmented browser or DNS over HTTPS on/off, restarting the app/phone or clearing the cache does not help unfortunately.
When trying to delete a manga, it just fails.
Trying to download a manga just crashes the app.

**Stack trace / LogCat**:
```ruby
delete log : begin
Hentoid ver: 1.18.3 (672)
API: 31
Device: GM1913
Start : 2023-08-20T15:07:33.160Z
End : 2023-08-20T15:07:33.601Z (00:00)
-----
worker created
Queue JSON successfully saved
Worker destroyed / stopped=false / complete=true
delete log : end
```
```ruby
latest-crash log : begin
Hentoid ver: 1.18.3 (672)
API: 31
Device: GM1913
Start : 2023-08-20T15:07:16.463Z
End : 2023-08-20T15:07:16.463Z (00:00)
-----
Could not put
io.objectbox.exception.DbFullException: Could not put (error code -30792)
	at io.objectbox.Cursor.collect004000(Native Method)
	at me.devsaki.hentoid.database.domains.ContentCursor.put(SourceFile:0)
	at me.devsaki.hentoid.database.domains.ContentCursor.put(SourceFile:0)
	at io.objectbox.Box.put(SourceFile:0)
	at me.devsaki.hentoid.database.ObjectBoxDB.updateContentStatus(Unknown Source:32)
	at me.devsaki.hentoid.database.ObjectBoxDAO.updateContentStatus(Unknown Source:2)
	at me.devsaki.hentoid.viewmodels.QueueViewModel.unpauseQueue(Unknown Source:6)
	at me.devsaki.hentoid.fragments.queue.QueueFragment.onCreateView$lambda$2(Unknown Source:21)
	at me.devsaki.hentoid.fragments.queue.QueueFragment.$r8$lambda$JjMy5BdF-bWr3DePxFXhCugMRZo(SourceFile:0)
	at me.devsaki.hentoid.fragments.queue.QueueFragment$$ExternalSyntheticLambda19.onClick(SourceFile:0)
	at android.view.View.performClick(View.java:7488)
	at android.view.View.performClickInternal(View.java:7464)
	at android.view.View.access$3700(View.java:841)
	at android.view.View$PerformClick.run(View.java:28911)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

latest-crash log : end
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Look like your collection has gotten too large for the app. The log says you've hit the database limit.

I advise you to :
1/ remove/backup some of your books
2/ once it's done, reinstall the app from scratch and reimport your library

**Comment by ImAWerewolfDuck** [comment]
Ah, I see. Is it pos

**Comment by RobbWatershed** [comment]
2GB is already rather large for a mobile database. It's two times the default value set by the vendor.

I fear performance will eventually plummet if we push it too far.

**Comment by ImAWerewolfDuck** [comment]
Would it be possible to enlarge the limit manually on my side? Or delete some mangas manually from the database (as I cant in the app) so my download queue does not get lost?
And reinstalling the app is not really feasible as I would lose progress of what I have already downloaded so far, which is why I would avoid it if possible.

**Comment by RobbWatershed** [comment]
You can reinstall from scratch, your collection and queue are safe and won't be deleted (all metadata are inside those JSON files you can find here and there in the Hentoid folder).

If you have custom settings, you can export them using **Tools > Export settings**

**Comment by ImAWerewolfDuck** [comment]
Now I am a bit confused:
My collection (and therefore database) is too big, so I should remove some books and reinstall.
But reinstalling keeps the collection?
Or does it just keep the currently in the device storage present books?
Because I mainly want to keep track of what I already have downloaded, as I move the downloaded files to my pc after a while anyways.

Sorry for the bother :/

**Comment by RobbWatershed** [comment]
Say you have, for example, 45K books.
1/ Uninstall
2/ Manually remove 10K books from the Hentoid folder to get back to 35K (e.g. [transfer them to your computer](https://github.com/avluis/Hentoid/wiki/Transferring-your-collection-between-devices))
3/ Reinstall and import your library back

If by "keep track of downloaded stuff" you mean "keep every single book you ever downloaded in the Hentoid library, in downloaded or streamed form" then I have no solution for you. You'll have to prune books in some way or another.
