### ISSUE TITLE
Apps Always back to home

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#1118]
Since the last 4 new update there's like a bug when I'm away from apps and always back to home when open the hentoid again

Before :
>The apps auto lock "since i set the timer 30sec" but when i input the password it only needs 1 time and opennes last thing I've been left like i searching on Nhentai or reading on my library

Now :
>The apps also auto lock "i set same like before 30sec" but whenever i was away when i opened the apps again it always takes me to "Home Page" instead the last thing i open or i read

Here's the example :
Https://streamable.com/475qd3
 

Sorry i cant upload the video here it said my video are to big

**Comment by Chocolalolz** [comment]
Here :

latest-crash log : begin
Hentoid ver: 1.18.10 (693)
API: 30
Device: Infinix X663B
Start : 2023-11-16T00:12:55.370Z
End : 2023-11-16T00:12:55.371Z (00:00)
-----
null cannot be cast to non-null type android.content.Intent
java.lang.NullPointerException: null cannot be cast to non-null type android.content.Intent
	at me.devsaki.hentoid.activities.UnlockActivity.goToNextActivity(Unknown Source:18)
	at me.devsaki.hentoid.activities.UnlockActivity.onUnlockSuccess(Unknown Source:6)
	at me.devsaki.hentoid.fragments.pin.UnlockPinDialogFragment.onPinAccept(Unknown Source:22)
	at me.devsaki.hentoid.fragments.pin.PinDialogFragment.onKeyClick(Unknown Source:53)
	at me.devsaki.hentoid.fragments.pin.PinDialogFragment.onCreateView$lambda$11$lambda$0(Unknown Source:7)
	at me.devsaki.hentoid.fragments.pin.PinDialogFragment.$r8$lambda$OfwGnsAlw2LxavLkUvX2kmWALfQ(SourceFile:0)
	at me.devsaki.hentoid.fragments.pin.PinDialogFragment$$ExternalSyntheticLambda8.onClick(SourceFile:0)
	at android.view.View.performClick(View.java:7472)
	at android.view.View.performClickInternal(View.java:7445)
	at android.view.View.access$3600(View.java:820)
	at android.view.View$PerformClick.run(View.java:28538)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:268)
	at android.app.ActivityThread.main(ActivityThread.java:8107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

latest-crash log : end

**Comment by Chocolalolz** [comment]
Here : 

-
[latest-crash_log.txt](https://github.com/avluis/Hentoid/files/13370887/latest-crash_log.txt)

**Comment by RobbWatershed** [comment]
I found the issue. It should be fixed for next release. Thanks for your feedback.

**Comment by RobbWatershed** [comment]
Fix is available on today's v1.18.13
