### ISSUE TITLE
force close when choosing Hentoid folder

### ISSUE THREAD

**Issue by afrizal1221** [avluis/Hentoid#670]
**Hentoid Version**:hentoid1127-257

**Device/Android Version**:Xiaomi Mi A2/ Android 10

**Issue details / Repro steps**:Force Close when choosing hentoid directory

**Stack trace / LogCat**:
time: 1603024118931
msg: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE (has extras) }
stacktrace: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2064)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
	at android.app.Activity.startActivityForResult(Activity.java:5210)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
	at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:795)
	at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:932)
	at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1279)
	at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1267)
	at me.devsaki.hentoid.util.ImportHelper.openFolderPicker(ImportHelper.java:82)
	at me.devsaki.hentoid.fragments.intro.ImportIntroFragment$onViewCreated$1.onClick(ImportIntroFragment.kt:38)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27896)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for your feedback. That's a tough one, as the bug you're describing is a aberration - Xiaomi decided not to map `OPEN_DOCUMENT_TREE` to any built-in screen, which is against the Android framework guidelines.

We'll check if a workaround exists, but we don't promise anthing.

**Comment by afrizal1221** [comment]
sure thing. good luck sir

**Comment by afrizal1221** [comment]
solved sir by installing an app called DocumentsUI.apk

**Comment by RobbWatershed** [comment]
Good to know ! Thanks for your feedback

**Comment by ayush19283** [comment]
> solved sir by installing an app called DocumentsUI.apk

which version sir?
